#!/bin/bash

echo 'fossfrog'>/etc/hostname
echo -e 'nameserver 8.8.8.8\nnameserver 8.8.4.4'>/etc/resolv.conf

echo '[*]Updating...'
apt update
apt upgrade -y

echo '[*]Installing Base and Phosh Packages...'
apt install -y kali-linux-core phosh-phone pinephone-support wget curl rsync systemd-timesyncd

mkdir -p /etc/skel/.local/share/squeekboard/keyboards/terminal
curl https://raw.githubusercontent.com/Shubhamvis98/PinePhone_Tweaks/main/layouts/us.yaml > /etc/skel/.local/share/squeekboard/keyboards/us.yaml
ln -sr /etc/skel/.local/share/squeekboard/keyboards/us.yaml /etc/skel/.local/share/squeekboard/keyboards/terminal/us.yaml

echo '[*]Adding User:kali, pass:8888...'
adduser --disabled-password --gecos "" kali
usermod --password `echo 8888 | openssl passwd -1 -stdin` kali
usermod -aG dialout,sudo,audio,video,plugdev,input,render,bluetooth,feedbackd kali

sed -i 's/-0.07/0/;s/-0.13/0/' /usr/share/plymouth/themes/kali/kali.script
sed -i 's/bash/zsh/' /etc/passwd

echo '[*]Enabling kali plymouth theme...'
plymouth-set-default-theme -R kali

echo '[*]Update u-boot config...'
u-boot-update

for i in phosh eg25-manager ssh systemd-repart
do
	systemctl enable $i
done
echo > /etc/resolv.conf
apt clean

mkdir -p /etc/repart.d
cat << 'EOF' > /etc/repart.d/50-root.conf
[Partition]
Type=root
Weight=10000
EOF

echo '[*]Changing Wallpaper to Kali...'
sed -i "/picture-uri/cpicture-uri='file:\/\/\/usr\/share\/backgrounds\/kali\/kali-red-sticker-16x9.jpg'" /usr/share/glib-2.0/schemas/11_mobile.gschema.override
glib-compile-schemas /usr/share/glib-2.0/schemas

