#!/bin/bash

cd `dirname $0`

echo 'kali'>/etc/hostname
echo -e 'nameserver 8.8.8.8\nnameserver 8.8.4.4'>/etc/resolv.conf

echo '[*]Updating...'
echo 'deb http://kali.download/kali kali-rolling main non-free contrib' > /etc/apt/sources.list
apt update
apt upgrade -y

echo '[*]Installing Base and Phosh Packages...'
apt install -y kali-linux-core kali-defaults phosh-phone pinephone-tweaks u-boot-menu rsync wget curl vim gnome-text-editor megapixels systemd-timesyncd inetutils-ping libcanberra-pulse firmware-realtek-rtl8723cs-bt eg25-manager
ln -rs /usr/share/alsa/ucm2/PinePhone/PinePhone.conf /usr/share/alsa/ucm2/conf.d/simple-card/

echo '[*]Adding User:kali, pass:8888...'
adduser --disabled-password --gecos "" kali
usermod --password `echo 8888 | openssl passwd -1 -stdin` kali
usermod -aG dialout,sudo,audio,video,plugdev,input,render,bluetooth,feedbackd kali

sed -i 's/-0.07/0/;s/-0.13/0/' /usr/share/plymouth/themes/kali/kali.script
sed -i 's/bash/zsh/' /etc/passwd

echo '[*]Copying Configs...'
rsync -HPavzl confs/ /

echo '[*]Enabling kali plymouth theme...'
plymouth-set-default-theme kali

echo '[*]Installing Extra Packages(kernel, alsa-ucm-conf etc)...'
for i in `ls debs | grep '\.deb'`
do
	apt install -y ./debs/$i
done

chown kali:kali -R /home/kali

echo '[*]Update u-boot config...'
u-boot-update

for i in $(cat svcs)
do
	systemctl enable $i
done
echo > /etc/resolv.conf
apt clean

echo '[*]Changing Wallpaper to Kali...'
sed -i "/picture-uri/cpicture-uri='file:\/\/\/usr\/share\/backgrounds\/kali\/kali-layers.xml'" /usr/share/glib-2.0/schemas/11_mobile.gschema.override
glib-compile-schemas /usr/share/glib-2.0/schemas

