#!/bin/sh

set -e

version="$1"
kernel="$2"

if [ -e "${kernel}" ]
then
	# Kernel still exists, meaning it's being upgraded, not
	# uninstalled; quit as we have nothing to do in such cases
	exit 0
fi

dtbdir="/boot/dtb-${version}"

# DTBs are synced if /boot is on a different partition than /
# Ensure there's no leftover when removing a kernel
if [ "$(stat --printf %d /)" != "$(stat --printf %d /boot)" ]
then
	if [ -d "${dtbdir}" ]
	then
		# Kernel has been removed, delete DTBs
		echo "I: u-boot-menu: removing ${dtbdir}"
		rm -rf "${dtbdir}"
	fi
fi

# Exit if extlinux was removed (!= purged)
if [ -x /usr/sbin/u-boot-update ]
then
	# Update extlinux configuration
	u-boot-update
fi
